NEVER TRUST FRONTEND USE MIDDLEWARE TO CHECK PERMISSION
CHECK ROLE OF USER
CHECK IF USER HAS PERMISSION TO ACCESS THIS RESOURCE
CHECK IF USER HAS PERMISSION TO PERFORM THIS ACTION
CHECK IF USER HAS PERMISSION TO VIEW THIS DATA