name: Supa-backup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      supabase_db_url: ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set date folder name
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create backup folder
        run: mkdir -p backup/$DATE

      - name: Backup roles
        run: supabase db dump --db-url "$supabase_db_url" -f backup/$DATE/roles.sql --role-only

      - name: Backup schema
        run: supabase db dump --db-url "$supabase_db_url" -f backup/$DATE/schema.sql

      - name: Backup data
        run: supabase db dump --db-url "$supabase_db_url" -f backup/$DATE/data.sql --data-only --use-copy

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Supabase backup (${{ env.DATE }})"